# Generated by Django 4.0.4 on 2022-05-22 09:37

from django.db import migrations, models
import pytz


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_post_body_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Date',
            field=models.DateTimeField(blank=True, default=pytz.timezone),
        ),
    ]
