# Generated by Django 4.0.4 on 2022-05-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Body',
            field=models.TextField(blank=True, max_length=10000),
        ),
    ]
